// Boulder Dash levels — generated, validated (well-formed + solvable).
// Legend: W steel  . dirt  (space) empty  r boulder  d diamond  P player  E exit  f firefly
window.BD_LEVELS = [
  {
    name: "First Dig",
    time: 150,
    need: 6,
    map: [
      "WWWWWWWWWWWWWWWW",
      "Wr...........d.W",
      "WrP.......d....W",
      "W.....rd.......W",
      "W.......d..r...W",
      "W..............W",
      "W.d............W",
      "W..d.d..r......W",
      "W......d....d..W",
      "W........d.....W",
      "W....r........EW",
      "WWWWWWWWWWWWWWWW",
    ].join("\n"),
  },
  {
    name: "Rockfall",
    time: 150,
    need: 9,
    map: [
      "WWWWWWWWWWWWWWWWWW",
      "W..rr...dr...r.d.W",
      "W.P........r.....W",
      "W...d..r........rW",
      "W................W",
      "W.........r......W",
      "Wd....r....r.r.d.W",
      "Wd..........d....W",
      "W..   .......d.d.W",
      "W.. f .d..r..r...W",
      "W..   ..rd.......W",
      "W.rd.......r.d..EW",
      "WWWWWWWWWWWWWWWWWW",
    ].join("\n"),
  },
  {
    name: "The Caverns",
    time: 145,
    need: 12,
    map: [
      "WWWWWWWWWWWWWWWWWWWW",
      "Wr........r........W",
      "W.P..drd.....r.....W",
      "Wd.r....d.drr..r   W",
      "W.....dr.d.....d f W",
      "W.............r.   W",
      "Wrr..r.r   ...r.r..W",
      "W......r f .d.....rW",
      "W...d..r   ..d.r...W",
      "W..dr.r............W",
      "Wr......rr...d.d...W",
      "W...r.......rd.....W",
      "W..r...d.......d..EW",
      "WWWWWWWWWWWWWWWWWWWW",
    ].join("\n"),
  },
  {
    name: "Bug Hunt",
    time: 135,
    need: 15,
    map: [
      "WWWWWWWWWWWWWWWWWWWW",
      "W......d..r.r.d....W",
      "W.P.......r.dr.r.d.W",
      "W.dd..r   .r.r.....W",
      "W..d.rd f ..r.   .rW",
      "Wr....r   ..r. f ..W",
      "Wr..r.r....d..   ..W",
      "W.rr.d..d..r.d..rdrW",
      "W.r....r..d...r...rW",
      "Wr.   .r...dr......W",
      "Wr. f ....r....d..rW",
      "Wd.   ......drrr...W",
      "W...dd.r.......d..EW",
      "WWWWWWWWWWWWWWWWWWWW",
    ].join("\n"),
  },
  {
    name: "Meltdown",
    time: 135,
    need: 18,
    map: [
      "WWWWWWWWWWWWWWWWWWWWWW",
      "W.......dr..r   .r..rW",
      "W.P...rrr.... f ..dd.W",
      "W..........r.   .rd..W",
      "W.r...r.   ...r.rr...W",
      "W.r..... f ....d.....W",
      "Wrr   d.   rdd...r.r.W",
      "W.r f .r.r..d.......rW",
      "W.r   .r...r.dr.drrr.W",
      "Wr..ddr....d.r.......W",
      "W.ddd......rr.   r...W",
      "W.rrd...d.dr.r f ..rrW",
      "Wd......ddrrd.   r.r.W",
      "W...r..d.......rdr..EW",
      "WWWWWWWWWWWWWWWWWWWWWW",
    ].join("\n"),
  },
];
